//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameVoteSolution.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gamevoteprojectEntities1 : DbContext
    {
        public gamevoteprojectEntities1()
            : base("name=gamevoteprojectEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Vote> Votes { get; set; }
        public virtual DbSet<Vote_Listing> Vote_Listing { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
