//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameVoteSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public Vote()
        {
            this.Vote_Listing = new HashSet<Vote_Listing>();
        }
    
        public int VoteID { get; set; }
        public Nullable<int> Placement_Left { get; set; }
        public Nullable<int> Placement_Right { get; set; }
        public int Win_Lose { get; set; }
        public int gameId { get; set; }
        public string Username { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual ICollection<Vote_Listing> Vote_Listing { get; set; }
    }
}
