//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameVoteSolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote_Listing
    {
        public int UserID { get; set; }
        public int VoteID { get; set; }
        public int GameID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Game Game { get; set; }
        public virtual Vote Vote { get; set; }
    }
}
