// <auto-generated />
namespace MeetUs.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddSpot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSpot));
        
        string IMigrationMetadata.Id
        {
            get { return "201404231454314_AddSpot"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
