//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace RateGames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Votes = new HashSet<Vote>();
        }
    
        [ScaffoldColumn(false)]
        public int gameID { get; set; }

        public string gameTitle { get; set; }
        public string gamePic { get; set; }
        public string gameQuote { get; set; }
    
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
